allowBuilds:
  sharp: true
auditConfig:
  ignoreGhsas:
    - 'GHSA-8h8q-6873-q5fj'
    - 'GHSA-mg66-mrh9-m8jx'
    - 'GHSA-c4j6-fc7j-m34r'
    - 'GHSA-492v-c6pp-mqqv'
    - 'GHSA-267c-6grr-h53f'
    - 'GHSA-36qx-fr4f-26g5'
    - 'GHSA-26hh-7cqf-hhc6'
    - 'GHSA-ffhc-5mcf-pf4q'
    - 'GHSA-gx5p-jg67-6x7h'
    - 'GHSA-h64f-5h5j-jqjh'
    - 'GHSA-wfc6-r584-vfw7'
    - 'GHSA-vfv6-92ff-j949'
    - 'GHSA-3g8h-86w9-wvmq'
    - 'GHSA-qx2v-qp2m-jg93'
